spring.application.name=tabmanager

spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres?user=postgres.dezsxtkfmcwxfhfpsfva&password=V268JhDaCITsutoO
spring.datasource.username=postgres.dezsxtkfmcwxfhfpsfva
spring.datasource.password=V268JhDaCITsutoO
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.autoconfigure.exclude=\
org.springframework.boot.liquibase.autoconfigure.LiquibaseAutoConfiguration